/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoverView: typeof import('./src/components/CoverView.vue')['default']
    GoBack: typeof import('./src/components/GoBack.vue')['default']
    MainBar: typeof import('./src/components/MainBar.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
  }
}
